kind: pipeline
name: node14

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: install
  image: node:14
  commands:
  - npm install

- name: test
  image: node:14
  commands:
  - make test

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
